Reacts to the update in the orchestrator-interface and updates certif…
canonical/magma-access-gateway-operator pull request #23
Opened 2023-02-07 14:25 UTC by saltiyazan

# Description

Reacts to the update in the orchestrator-interface and updates certifier cert.

- Adds test cases.
- Fixes tox issues

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added tests that validate the behaviour of the software.
- [x] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-02-07 16:03 UTC, ghislainbourgeois requested changes

2023-02-07 16:03 UTC, ghislainbourgeois commented on tests/unit/test_charm.py
> +        patch_remove.assert_not_called()
```suggestion
        self.assertNotIn(call().unlink(), patch_path.mock_calls)
```

2023-02-07 16:03 UTC, ghislainbourgeois commented on tests/unit/test_charm.py
> +    @patch("os.remove")
```suggestion
```

2023-02-07 16:03 UTC, ghislainbourgeois commented on tests/unit/test_charm.py
> +        patch_remove.assert_called()
```suggestion
        self.assertIn(call().unlink(), patch_path.mock_calls)
```

2023-02-08 07:32 UTC, saltiyazan commented on tests/unit/test_charm.py
> +        patch_remove.assert_called()
✅

2023-02-08 07:32 UTC, saltiyazan commented on tests/unit/test_charm.py
> +    @patch("os.remove")
✅

2023-02-08 07:32 UTC, saltiyazan commented on tests/unit/test_charm.py
> +        patch_remove.assert_not_called()
✅

2023-02-08 07:32 UTC, saltiyazan commented on tests/unit/test_charm.py
> +        self, patch_remove, patch_subprocess_run, patch_path
✅

2023-02-08 07:32 UTC, saltiyazan commented on tests/unit/test_charm.py
> +    @patch("os.remove")
✅

2023-02-08 07:32 UTC, saltiyazan commented on tests/unit/test_charm.py
> +
✅

2023-02-08 07:32 UTC, saltiyazan commented on src/charm.py
> +                os.remove(file)
✅

2023-02-08 07:32 UTC, saltiyazan commented on src/charm.py
> +import os
✅

2023-02-08 12:12 UTC, Gmerold approved these changes
You can make it a regular PR now ;)

2023-02-08 14:16 UTC, ghislainbourgeois approved these changes

2023-02-08 14:18 UTC, merged