Fixes python dependencies for 1.6 release.
canonical/magma-access-gateway-operator pull request #24
Opened 2023-02-07 14:56 UTC by sanchezfdezjavier

# Description

Fixes python dependencies for 1.6 release.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-02-07 15:09 UTC, ghislainbourgeois requested changes

2023-02-10 14:45 UTC, sanchezfdezjavier commented on tox.ini
> +    pytest-operator==0.23.0
I've created a `test-requirements.txt` for consistency.

2023-02-10 14:45 UTC, sanchezfdezjavier commented on tox.ini
> +    pytest==7.2.1
I've created a `test-requirements.txt` for consistency.

2023-02-10 14:45 UTC, sanchezfdezjavier commented on tox.ini
> +    pytest-operator==0.23.0
I've created a `test-requirements.txt` for consistency.

2023-02-13 09:06 UTC, saltiyazan approved these changes

2023-02-13 10:15 UTC, saltiyazan approved these changes

2023-02-13 10:16 UTC, merged