Fixes the docs to use juju3.x commands
canonical/magma-access-gateway-operator pull request #35
Opened 2023-02-15 13:09 UTC by saltiyazan

# Description

Fixes the docs to use juju3.x commands

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-02-15 13:37 UTC, gruyaume requested changes
The change doesn't match with the PR name

2023-02-15 13:46 UTC, saltiyazan commented
> The change doesn't match with the PR name

Changed the base to 1.6. it is now @gruyaume

2023-02-15 14:09 UTC, ghislainbourgeois approved these changes

2023-02-16 16:03 UTC, gruyaume approved these changes

2023-02-17 08:14 UTC, merged