Adding support for blocking/unblocking AGW local IPs
canonical/magma-access-gateway-operator pull request #46
Opened 2023-04-05 10:59 UTC by Gmerold

# Description

Adds support for blocking/unblocking AGW local IPs usage.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

2023-04-05 14:06 UTC, ghislainbourgeois requested changes

2023-04-06 07:59 UTC, Gmerold commented on src/charm.py
> +            if not self._is_configuration_valid:
We only check the config params relevant for the deployment of the AGW here. 
The only config that can change over time is blocking of the local IPs. This one however, is a boolean and the validation is enforced by Juju.

2023-04-06 09:51 UTC, Gmerold commented on src/charm.py
Agreed.
And actually I did some refactoring there:
1. I've added a separate callback for `ConfigChangedEvent`
2. The new callback only covers changing the value of the `block_agw_local_ips` param.
3. Removed handling of the networking config changes - those would only be applied if the `magmad` was down anyway, otherwise `_on_install` would return immediately. 
 
Let me know what you think about it.

2023-04-06 19:30 UTC, ghislainbourgeois approved these changes

2023-04-06 19:31 UTC, ghislainbourgeois commented on src/charm.py
This is great, thank you!

2023-04-10 12:20 UTC, gruyaume approved these changes

2023-04-11 07:16 UTC, merged